"""empty message

Revision ID: 08daa7acd9bd
Revises: a33c7cfead2e
Create Date: 2023-05-03 13:55:35.192398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08daa7acd9bd'
down_revision = 'a33c7cfead2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
