"""empty message

Revision ID: 42355fbebcad
Revises: b29430da66f2
Create Date: 2023-05-15 15:53:50.169376

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "42355fbebcad"
down_revision = "b29430da66f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("media_dir", sa.String(), nullable=True))
    op.drop_column("posts", "media")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("media", postgresql.BYTEA(), autoincrement=False, nullable=True),
    )
    op.drop_column("posts", "media_dir")
    # ### end Alembic commands ###
