"""empty message

Revision ID: 5768e7d152c2
Revises: f5826f2cef54
Create Date: 2023-05-19 18:26:25.686541

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "5768e7d152c2"
down_revision = "f5826f2cef54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "create_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("post_owner_id", sa.Integer(), nullable=False),
        sa.Column("votes", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_owner_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    # ### end Alembic commands ###
