"""add column phone_numbre to users table

Revision ID: 6f340cef98d4
Revises: 7446bf9b57cd
Create Date: 2023-02-03 15:07:50.145111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f340cef98d4'
down_revision = '7446bf9b57cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.create_unique_constraint("phone", 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_constraint(None, 'users', type_='unique')
    #
    # ### end Alembic commands ###
