"""empty message

Revision ID: 75200e767cb8
Revises: 879f446311f3
Create Date: 2023-04-26 13:57:56.311602

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "75200e767cb8"
down_revision = "879f446311f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("media", sa.LargeBinary(2048), nullable=True)
    )
    op.drop_column("posts", "title")
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    op.add_column(
        "posts", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("posts", "media")
    # ### end Alembic commands ###
