"""empty message

Revision ID: 99d4d4f0dd51
Revises: a4c8af484856
Create Date: 2023-05-19 20:49:27.112075

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "99d4d4f0dd51"
down_revision = "a4c8af484856"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
