"""empty message

Revision ID: a33c7cfead2e
Revises: 32d4ae55d6da
Create Date: 2023-05-03 11:22:03.239533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33c7cfead2e'
down_revision = '32d4ae55d6da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_dir', sa.String(), nullable=True))
    op.drop_column('posts', 'media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'media_dir')
    # ### end Alembic commands ###
