"""empty message

Revision ID: a4c8af484856
Revises: 5768e7d152c2
Create Date: 2023-05-19 18:45:27.798163

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "a4c8af484856"
down_revision = "5768e7d152c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("comments", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "comments")
    # ### end Alembic commands ###
