"""empty message

Revision ID: f5826f2cef54
Revises: fe74306eec3d
Create Date: 2023-05-16 15:07:46.679403

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f5826f2cef54"
down_revision = "fe74306eec3d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "media")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("media", postgresql.BYTEA(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
