"""empty message

Revision ID: fc47f86f4f4c
Revises: 08daa7acd9bd
Create Date: 2023-05-03 14:22:20.699839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc47f86f4f4c'
down_revision = '08daa7acd9bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media', sa.LargeBinary(), nullable=True))
    op.drop_column('posts', 'media_dir')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_dir', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'media')
    # ### end Alembic commands ###
