"""empty message

Revision ID: fe74306eec3d
Revises: 42355fbebcad
Create Date: 2023-05-15 17:12:23.891642

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "fe74306eec3d"
down_revision = "42355fbebcad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("media", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "media")
    # ### end Alembic commands ###
