name: Buld and deply code

on: 
  push:
    branches:
      -"main"
jobs:
  job1:
    runs-on: ubuntu-latest 
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      -name: say hi to julian
        run: echo "hello julian"
        
  